# Generated by Django 4.2.27 on 2026-01-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('creator', models.CharField(db_index=True, max_length=255)),
                ('member_count', models.IntegerField(default=0)),
                ('room_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_checked', models.BooleanField(db_index=True, default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='core.room')),
            ],
            options={
                'verbose_name': 'Room Check Log',
                'verbose_name_plural': 'Room Check Logs',
                'ordering': ['-checked_at'],
            },
        ),
    ]
