# Generated by Django 4.2.27 on 2026-01-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('teams', 'Teams'), ('matrix', 'Matrix')], db_index=True, max_length=20)),
                ('platform_room_id', models.CharField(db_index=True, help_text='Room/channel ID for the platform', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name of the room/channel', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
