# Generated by Django 4.2.27 on 2026-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="limits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plan",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
