# Generated by Django 4.2.27 on 2026-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_plan_limits_plan_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="limits",
        ),
        migrations.AddField(
            model_name="plan",
            name="daily_summary_quota_per_room",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="plan",
            name="number_of_rooms",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
