# Generated by Django 4.2.27 on 2026-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_plan_limits_plan_daily_summary_quota_per_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_at",
            field=models.DateField(),
        ),
    ]
