# Generated by Django 4.2.27 on 2026-01-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_subscription_end_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationProcessingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_message_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_summarized_at", models.DateTimeField(blank=True, null=True)),
                ("summary_pending", models.BooleanField(default=False)),
                ("summary_in_progress", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subscriberroom",
                    ),
                ),
            ],
        ),
    ]
