# Generated by Django 4.2.27 on 2026-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_conversationprocessingstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationprocessingstate",
            name="summary_in_progress",
        ),
        migrations.RemoveField(
            model_name="conversationprocessingstate",
            name="summary_pending",
        ),
        migrations.AddField(
            model_name="conversationprocessingstate",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conversationprocessingstate",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationprocessingstate",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("ready", "Ready"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="idle",
                max_length=20,
            ),
        ),
    ]
