# Generated by Django 4.2.27 on 2026-01-09 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0006_remove_conversationprocessingstate_summary_in_progress_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomDailySummaryCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summary_counts",
                        to="core.subscriberroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("room", "date")},
            },
        ),
    ]
