# Generated by Django 4.2.27 on 2026-01-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_roomdailysummarycount"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationprocessingstate",
            name="llm_context_to_process",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RoomSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("reply", models.TextField(blank=True, null=True)),
                ("needs_more_information", models.BooleanField(default=False)),
                ("todo_list", models.JSONField(blank=True, default=list)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("from_timestamp", models.DateTimeField(blank=True, null=True)),
                ("to_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="core.subscriberroom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Room summaries",
                "ordering": ["-created_at"],
            },
        ),
    ]
