# Generated by Django 4.2.27 on 2026-01-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_conversationprocessingstate_llm_context_to_process_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomsummary",
            name="send_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roomsummary",
            name="send_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomsummary",
            name="sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
