# Generated by Django 4.2.27 on 2026-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_roomsummary_send_error_roomsummary_send_failed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="matrix_room_id",
            field=models.CharField(
                blank=True,
                help_text="Matrix room ID for sending notifications (subscriber's WhatsApp)",
                max_length=255,
                null=True,
            ),
        ),
    ]
