# Generated by Django 4.2.27 on 2026-01-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_subscriber_matrix_room_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationprocessingstate",
            name="is_being_summarized",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True while room is in summarization pipeline, prevents re-queueing",
            ),
        ),
    ]
