# Generated by Django 4.2.27 on 2026-01-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_conversationprocessingstate_is_being_summarized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationprocessingstate",
            name="is_being_summarized",
        ),
    ]
