# Generated by Django 4.2.27 on 2026-01-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_conversationprocessingstate_is_being_summarized"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        choices=[("gpt-5.1", "GPT 5.1"), ("gemini-3", "Gemini 3")],
                        default="gpt-5.1",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
