# Generated by Django 4.2.27 on 2026-01-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_todolist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="core.subscriberroom",
            ),
        ),
    ]
