# Generated by Django 4.2.27 on 2026-01-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_todolist_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberroom",
            name="room_code",
            field=models.CharField(
                blank=True,
                help_text="Short code for the room (e.g., 'family', 'work')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriberroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_code__isnull", False)),
                fields=("subscriber", "room_code"),
                name="unique_subscriber_room_code",
            ),
        ),
    ]
